IS_APP_VERBOSE = True
APP_USER_VOCAL_FILE = 'user_vocals.wav'
APP_GPT_COMPLETION_VOCAL_FILE = 'gpt_vocals.wav'

GOOGLE_CLOUD_API_KEY = 'AIzaSyC4QoaghvlsSVKFeWV1eLuMHJRNpnMhweg'
GOOGLE_CLOUD_QUOTA_PROJECT_ID = 'sinuous-canto-375422'

CHAT_GPT_API_KEY = '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'
